---
  - name: installing and launching filebeat
    hosts: webservers
    become: true
    tasks:

    # download filebeat deb
    - name: download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

      # Install filebeat deb
    - name: install filebeat deb
      command: sudo dpkg -i filebeat-7.6.1-amd64.deb

      # drop in filebeat.yml
    - name: drop in filebeat.yml
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml


      # enable and configure system module
    - name: enable and configure system module
      command: sudo filebeat modules enable system


      # setup filebeat
    - name: setup filebeat
      command: sudo filebeat setup

      # start filebeat service
    - name: start filebeat service
      command: sudo service filebeat start

      # enable service filebeat on boot
    - name: enable service filebeat on boot
      systemd:
        name: docker
        enabled: yes
