---
  - name: Install metric beat
    hosts: webservers
    become: true
    tasks:

     # download metricbeat
     # Use command module

    - name: download metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      # Install metric beat
      # Use command module

    - name: install metricbeat
      command: dpkg -i metricbeat-7.6.1-amd64.deb

      # drop in metric beat config
      # use copy module

    - name: drop in metricbeat config
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml


      # enable and configure docker module for metric beat
      # use command module

    - name: enable and configure docker module for metric beat
      command: metricbeat modules enable docker


      # setup metricbeat
      # use command module
    - name: setup metricbeat
      command: metricbeat setup

      # enable service metricbeat on boot
      # Use systemd module
    - name: enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes
